spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/enterprise_oa_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: dadada
  redis:
    host: localhost
    port: 6379
    database: 1
server:
  port: 8081