spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/enterprise_oa_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Hongkong
    username: root
    password: dadada
server:
  port: 8008

  #mybatis-plus配置控制台打印完整带参数SQL语句
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl